name = "linkedtfin"
compatibility_date = "2024-04-05"
pages_build_output_dir = "dist"

[d1_databases]
[[d1_databases]]
binding = "DB"
database_name = "linkedtfin-db"
database_id = "to-be-generated"

[r2_buckets]
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "linkedtfin-assets"

[vars]
ENVIRONMENT = "production"
