name = "linked-tf-in-test"
compatibility_date = "2024-04-05"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "linkedtfin-db"
database_id = "3eaea36c-54bd-4db0-90ad-49615aef1220"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "linkedtfin-assets"

[vars]
ENVIRONMENT = "production"
